In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("sqdata.csv")

In [3]:
data

Unnamed: 0   num    square
0            NaN     0         0
1            NaN     1         1
2            NaN     2         4
3            NaN     3         9
4            NaN     4        16
5            NaN     5        25
6            NaN     6        36
7            NaN     7        49
8            NaN     8        64
9            NaN     9        81
10           NaN    10       100
11           NaN    11       121
12           NaN    12       144
13           NaN    13       169
14           NaN    14       196
15           NaN    15       225
16           NaN    16       256
17           NaN    17       289
18           NaN    18       324
19           NaN    19       361
20           NaN    20       400
21           NaN    21       441
22           NaN    22       484
23           NaN    23       529
24           NaN    24       576
25           NaN    25       625
26           NaN    26       676
27           NaN    27       729
28           NaN    28       784
29           NaN    29       841
...          ...   ...       ...
9970         NaN  9970  99400900
9971         NaN  9971  99420841
9972         NaN  9972  99440784
9973         NaN  9973  99460729
9974         NaN  9974  99480676
9975         NaN  9975  99500625
9976         NaN  9976  99520576
9977         NaN  9977  99540529
9978         NaN  9978  99560484
9979         NaN  9979  99580441
9980         NaN  9980  99600400
9981         NaN  9981  99620361
9982         NaN  9982  99640324
9983         NaN  9983  99660289
9984         NaN  9984  99680256
9985         NaN  9985  99700225
9986         NaN  9986  99720196
9987         NaN  9987  99740169
9988         NaN  9988  99760144
9989         NaN  9989  99780121
9990         NaN  9990  99800100
9991         NaN  9991  99820081
9992         NaN  9992  99840064
9993         NaN  9993  99860049
9994         NaN  9994  99880036
9995         NaN  9995  99900025
9996         NaN  9996  99920016
9997         NaN  9997  99940009
9998         NaN  9998  99960004
9999         NaN  9999  99980001

[10000 rows x 3 columns]

In [4]:
x=data['num'].values
y=data['square'].values

In [5]:
x

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [6]:
y

array([       0,        1,        4, ..., 99940009, 99960004, 99980001])

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
xTrain,xTest,yTrain,yTest = train_test_split(x,y,test_size = 0.3, random_state=42)

In [9]:
len(xTrain)

7000

In [10]:
from sklearn.preprocessing import PolynomialFeatures

In [11]:
poly = PolynomialFeatures(degree=2)
xpoly = poly.fit_transform(xTrain.reshape(-1,1))

In [12]:
poly.fit(xpoly,y)

PolynomialFeatures(degree=2, include_bias=True, interaction_only=False)

In [15]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(xpoly,yTrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [20]:
xtestpoly = poly.fit_transform(xTest.reshape(-1,1))

In [21]:
pred = linreg.predict(xtestpoly)

In [31]:
yPred = [int(round(data)) for data in pred]
yPred = np.array(yPred)
yPred

array([39087504, 21939856,  2996361, ...,  9381969, 42081169, 22137025])

In [29]:
yTest

array([39087504, 21939856,  2996361, ...,  9381969, 42081169, 22137025])

In [32]:
accuracy_score(yTest, yPred)

1.0